### ISSUE TITLE
How to get the client_secret ?

### ISSUE THREAD

**Issue by JsHuang** [microsoft/onefuzz-samples#3]
In the ["Example Github Actions Pipeline"](https://github.com/microsoft/onefuzz-samples/blob/main/github-pipeline.yml), there is a `--client_secret` in the onefuzz command . 
```
...
onefuzz config --endpoint $ONEFUZZ_ENDPOINT --client_id $ONEFUZZ_CLIENT_ID --client_secret $ONEFUZZ_CLIENT_SECRET
...
```
But I don't konw how to get it , after deploying the OneFuzz instance, I only get results like that:
```
INFO:deploy:Update your CLI config via: onefuzz config --endpoint https://xxx.azurewebsites.net --authority https://login.microsoftonline.com/xxx --client_id xxx
```

**Comment by bmc-msft** [comment]
@JsHuang, Sorry for the delay in response.

When you deploy OneFuzz, you're provided the configuration required to enable using Onefuzz via "public client" mode of [Microsoft Identity device authorization](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code).  

If you would like to use a client secret method, you'll need to register an app to do that.  See [Register an application with the Microsoft identity platform](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app).

In the future, please use the [OneFuzz Issues](https://github.com/microsoft/onefuzz/issues) in the future.  Thanks!
